-- 二手iPhone回收报价对比网站 · Supabase 建表语句
-- 在 Supabase 后台 → SQL Editor 中完整执行本文件

-- 1. 创建报价表
create table public.iphone_quote (
  id bigint generated by default as identity primary key,
  model text not null,                        -- 机型：iPhone 17 PRO MAX
  network_model text,                         -- 网络型号 A3527
  storage text not null,                      -- 容量：256G / 512G / 1T / 2T
  price_high_keep_new integer,                -- 高保充新
  price_good integer,                         -- 靓机
  price_small_scratch integer,                -- 小花
  price_big_scratch integer,                  -- 大花
  price_out_break integer,                    -- 外爆
  price_inner_break integer,                  -- 内爆可测
  color_deduct text,                          -- 颜色差价：蓝色-400
  note_deduct text,                           -- 备注扣费：无全套扣费
  source text not null,                       -- 报价来源：手机联盟/爱回收/转转
  update_time timestamp with time zone default now(),  -- 报价更新时间
  status text default 'pending',              -- pending待审核 / approved已公开 / rejected驳回
  created_at timestamp with time zone default now()
);

-- 2. 开启行级安全策略 RLS
alter table public.iphone_quote enable row level security;

-- 3. 公开用户只能查询已审核通过的数据
create policy "public read approved"
on public.iphone_quote for select
to anon
using (status = 'approved');

-- 4. 匿名访客可提交新报价（无需登录，提交后直接公开）
create policy "anon insert"
on public.iphone_quote for insert
to anon
with check (true);

-- 5. 匿名访客可以更新记录（编辑已有报价）
create policy "anon update"
on public.iphone_quote for update
to anon
using (true)
with check (true);

-- 6. 匿名访客可以删除记录
create policy "anon delete"
on public.iphone_quote for delete
to anon
using (true);

-- 安全说明：本方案取消管理员审核机制，任何人都可以直接增删改报价数据。
-- 如果后续需要恢复审核流程，删除上述 4/5/6 策略，改为 to authenticated 即可。
-- 建议在前端加一道简单口令验证防止恶意篡改。

-- 7. 历史版本补丁：若此前执行过旧版本策略，以下语句会清理旧策略；全新执行时为无副作用空操作。
drop policy if exists "allow insert for authenticated" on public.iphone_quote;
drop policy if exists "anon insert pending" on public.iphone_quote;
drop policy if exists "authenticated insert" on public.iphone_quote;
drop policy if exists "authenticated read all" on public.iphone_quote;
drop policy if exists "authenticated update" on public.iphone_quote;
drop policy if exists "authenticated delete" on public.iphone_quote;
