-- 二手iPhone回收报价对比网站 · Supabase 建表语句
-- 在 Supabase 后台 → SQL Editor 中完整执行本文件

-- 1. 创建报价表
create table public.iphone_quote (
  id bigint generated by default as identity primary key,
  model text not null,                        -- 机型：iPhone 17 PRO MAX
  network_model text,                         -- 网络型号 A3527
  storage text not null,                      -- 容量：256G / 512G / 1T / 2T
  price_high_keep_new integer,                -- 高保充新
  price_good integer,                         -- 靓机
  price_small_scratch integer,                -- 小花
  price_big_scratch integer,                  -- 大花
  price_out_break integer,                    -- 外爆
  price_inner_break integer,                  -- 内爆可测
  color_deduct text,                          -- 颜色差价：蓝色-400
  note_deduct text,                           -- 备注扣费：无全套扣费
  source text not null,                       -- 报价来源：手机联盟/爱回收/转转
  update_time timestamp with time zone default now(),  -- 报价更新时间
  status text default 'pending',              -- pending待审核 / approved已公开 / rejected驳回
  created_at timestamp with time zone default now()
);

-- 2. 开启行级安全策略 RLS
alter table public.iphone_quote enable row level security;

-- 3. 公开用户只能查询已审核通过的数据
create policy "public read approved"
on public.iphone_quote for select
to anon
using (status = 'approved');

-- 4. 匿名访客可提交新报价（强制为 pending 待审核，防止匿名直接写入已公开数据）
create policy "anon insert pending"
on public.iphone_quote for insert
to anon
with check (status = 'pending');

-- 4.1 登录用户（管理员）可插入任意状态记录（用于修复/补录数据）
create policy "authenticated insert"
on public.iphone_quote for insert
to authenticated
with check (true);

-- 5. 登录用户（管理员）可以读取全部记录（含待审核/驳回）
create policy "authenticated read all"
on public.iphone_quote for select
to authenticated
using (true);

-- 6. 登录用户（管理员）可以更新记录（审核通过/驳回）
create policy "authenticated update"
on public.iphone_quote for update
to authenticated
using (true)
with check (true);

-- 7. 登录用户（管理员）可以删除记录
create policy "authenticated delete"
on public.iphone_quote for delete
to authenticated
using (true);

-- 安全说明：Supabase 默认关闭公开注册（Authentication → Sign Up / Providers 中 Email 注册默认关闭），
-- 登录账号只能由管理员在 Authentication → Users → Add user 手动创建，
-- 因此上述 authenticated 读写权限实际仅管理员持有，请勿开启公开注册。

-- 8. 历史版本补丁：若此前执行过旧版本（insert 仅允许 authenticated，导致匿名提交报价失败），
--    本段会删除旧策略；全新执行时此段为无副作用的空操作。
drop policy if exists "allow insert for authenticated" on public.iphone_quote;
